# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 AVANTRO s.r.o.
"""
Static country reference data.

This module is GENERATED - do not edit by hand. Reproduce it with:

    pip install phonenumbers Babel
    python tools/update_countries.py --oas <path to a checkout of github.com/Foxentry/OAS>

The generator is deterministic: same inputs, same bytes. `--check` verifies that this file
is up to date without writing anything, which is what CI runs.

The data is baked into the build on purpose: the application must never reach out
to the network at runtime except for the validation calls the user explicitly starts.
Sources: the Foxentry OpenAPI specification (per-service `dataSource` defaults),
ITU-T E.164 calling codes and their primary countries (via `phonenumbers`), and CLDR country
names (via `Babel`). Postal-code shapes, legal-form suffixes and neighbouring countries are
curated in the generator.

Contents
--------
COVERAGE          which countries each Foxentry service supports
CALLING_CODES     ISO 3166-1 alpha-2 -> E.164 calling code
PREFIX_TO_COUNTRY calling code -> the country we treat as primary for detection
NAMES_EN/NAMES_CS country names (English is the default; Czech is a translation)
ZIP_PATTERNS      postal-code shape per country (used to detect the country from data)
COMPANY_SUFFIXES  legal-form suffixes per country (weak detection signal)
NEIGHBOURS        neighbouring countries (used when ranking phone prefixes)
"""

from __future__ import annotations

import re

WORLDWIDE = "worldwide"

# --- Service coverage -------------------------------------------------------
# Mirrors the `dataSource` defaults in the Foxentry OpenAPI specification.
# Sending a country a service does not cover only burns credits and returns
# "invalid" for every row, so the wizard warns the user up front.
COVERAGE: dict[str, list[str] | str] = {
    'email': WORLDWIDE,
    'phone': WORLDWIDE,
    'name': ['CZ', 'SK'],
    'company': ['CZ', 'HU', 'PL', 'SK'],
    'location': ['AD', 'AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'ES', 'FR', 'GB', 'GR', 'HR', 'HU', 'IS', 'IT', 'LI', 'LU', 'MC', 'ME', 'MK', 'MT', 'NL', 'PL', 'RO', 'RS', 'SI', 'SK', 'SM', 'VA', 'XK'],
}

# Whether an uncovered country fails hard (a register) or merely degrades
# (reference data such as names).
STRICT_COVERAGE: dict[str, bool] = {
    'location': True,
    'company': True,
    'name': False,
}

def is_strict(service: str) -> bool:
    return STRICT_COVERAGE.get(service, True)


def supports(service: str, country: str | None) -> bool:
    """True when the service can validate data from that country."""
    cov = COVERAGE.get(service, WORLDWIDE)
    if cov == WORLDWIDE:
        return True
    if not country:
        return True  # no country chosen -> the API searches every source
    return country.upper() in cov


def covered_countries(service: str) -> list[str]:
    """The countries a service covers ([] means worldwide)."""
    cov = COVERAGE.get(service, WORLDWIDE)
    return [] if cov == WORLDWIDE else list(cov)


# --- Names ------------------------------------------------------------------
def name(code: str, lang: str = "en") -> str:
    """Country name in the requested language; English is the fallback."""
    code = (code or "").upper()
    if lang == "cs":
        return NAMES_CS.get(code) or NAMES_EN.get(code) or code
    return NAMES_EN.get(code) or code


def flag(code: str) -> str:
    """Regional-indicator flag emoji for an alpha-2 code."""
    code = (code or "").upper()
    if not re.fullmatch(r"[A-Z]{2}", code):
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - 65) for ch in code)


# --- Phone prefixes ---------------------------------------------------------
def prefix_of(country: str | None) -> str | None:
    """E.164 calling code for a country, e.g. "CZ" -> "+420"."""
    return CALLING_CODES.get((country or "").upper())


def country_of_prefix(number: str) -> str | None:
    """
    Country for a phone number written with an international prefix.
    Longest match wins, so "+420" beats "+42".
    """
    value = re.sub(r"[^\d+]", "", number or "")
    if not value.startswith("+"):
        return None
    for length in range(5, 1, -1):
        hit = PREFIX_TO_COUNTRY.get(value[:length])
        if hit:
            return hit
    return None


def prefix_order(country: str | None) -> list[str]:
    """
    Preferred prefixes for the API, most likely first.

    Only used for numbers written WITHOUT a prefix: the API picks the first
    prefix from this list that makes the number valid.
    """
    order: list[str] = []
    own = prefix_of(country)
    if own:
        order.append(own)
    for neighbour in NEIGHBOURS.get((country or "").upper(), ()):
        pfx = prefix_of(neighbour)
        if pfx and pfx not in order:
            order.append(pfx)
    return order


# --- Postal codes -----------------------------------------------------------
def zip_matches(country: str, value: str) -> bool:
    """True when the value has the shape of that country's postal code."""
    pattern = ZIP_PATTERNS.get((country or "").upper())
    if not pattern or not value:
        return False
    return bool(re.fullmatch(pattern, value.strip(), re.IGNORECASE))


def countries_matching_zip(value: str) -> list[str]:
    """Every country whose postal-code shape the value fits."""
    value = (value or "").strip()
    if not value:
        return []
    return [cc for cc, pat in ZIP_PATTERNS.items()
            if re.fullmatch(pat, value, re.IGNORECASE)]

# --- Generated data ---------------------------------------------------------
CALLING_CODES: dict[str, str] = {
    'AC': '+247',
    'AD': '+376',
    'AE': '+971',
    'AF': '+93',
    'AG': '+1',
    'AI': '+1',
    'AL': '+355',
    'AM': '+374',
    'AO': '+244',
    'AR': '+54',
    'AS': '+1',
    'AT': '+43',
    'AU': '+61',
    'AW': '+297',
    'AX': '+358',
    'AZ': '+994',
    'BA': '+387',
    'BB': '+1',
    'BD': '+880',
    'BE': '+32',
    'BF': '+226',
    'BG': '+359',
    'BH': '+973',
    'BI': '+257',
    'BJ': '+229',
    'BL': '+590',
    'BM': '+1',
    'BN': '+673',
    'BO': '+591',
    'BQ': '+599',
    'BR': '+55',
    'BS': '+1',
    'BT': '+975',
    'BW': '+267',
    'BY': '+375',
    'BZ': '+501',
    'CA': '+1',
    'CC': '+61',
    'CD': '+243',
    'CF': '+236',
    'CG': '+242',
    'CH': '+41',
    'CI': '+225',
    'CK': '+682',
    'CL': '+56',
    'CM': '+237',
    'CN': '+86',
    'CO': '+57',
    'CR': '+506',
    'CU': '+53',
    'CV': '+238',
    'CW': '+599',
    'CX': '+61',
    'CY': '+357',
    'CZ': '+420',
    'DE': '+49',
    'DJ': '+253',
    'DK': '+45',
    'DM': '+1',
    'DO': '+1',
    'DZ': '+213',
    'EC': '+593',
    'EE': '+372',
    'EG': '+20',
    'EH': '+212',
    'ER': '+291',
    'ES': '+34',
    'ET': '+251',
    'FI': '+358',
    'FJ': '+679',
    'FK': '+500',
    'FM': '+691',
    'FO': '+298',
    'FR': '+33',
    'GA': '+241',
    'GB': '+44',
    'GD': '+1',
    'GE': '+995',
    'GF': '+594',
    'GG': '+44',
    'GH': '+233',
    'GI': '+350',
    'GL': '+299',
    'GM': '+220',
    'GN': '+224',
    'GP': '+590',
    'GQ': '+240',
    'GR': '+30',
    'GT': '+502',
    'GU': '+1',
    'GW': '+245',
    'GY': '+592',
    'HK': '+852',
    'HN': '+504',
    'HR': '+385',
    'HT': '+509',
    'HU': '+36',
    'ID': '+62',
    'IE': '+353',
    'IL': '+972',
    'IM': '+44',
    'IN': '+91',
    'IO': '+246',
    'IQ': '+964',
    'IR': '+98',
    'IS': '+354',
    'IT': '+39',
    'JE': '+44',
    'JM': '+1',
    'JO': '+962',
    'JP': '+81',
    'KE': '+254',
    'KG': '+996',
    'KH': '+855',
    'KI': '+686',
    'KM': '+269',
    'KN': '+1',
    'KP': '+850',
    'KR': '+82',
    'KW': '+965',
    'KY': '+1',
    'KZ': '+7',
    'LA': '+856',
    'LB': '+961',
    'LC': '+1',
    'LI': '+423',
    'LK': '+94',
    'LR': '+231',
    'LS': '+266',
    'LT': '+370',
    'LU': '+352',
    'LV': '+371',
    'LY': '+218',
    'MA': '+212',
    'MC': '+377',
    'MD': '+373',
    'ME': '+382',
    'MF': '+590',
    'MG': '+261',
    'MH': '+692',
    'MK': '+389',
    'ML': '+223',
    'MM': '+95',
    'MN': '+976',
    'MO': '+853',
    'MP': '+1',
    'MQ': '+596',
    'MR': '+222',
    'MS': '+1',
    'MT': '+356',
    'MU': '+230',
    'MV': '+960',
    'MW': '+265',
    'MX': '+52',
    'MY': '+60',
    'MZ': '+258',
    'NA': '+264',
    'NC': '+687',
    'NE': '+227',
    'NF': '+672',
    'NG': '+234',
    'NI': '+505',
    'NL': '+31',
    'NO': '+47',
    'NP': '+977',
    'NR': '+674',
    'NU': '+683',
    'NZ': '+64',
    'OM': '+968',
    'PA': '+507',
    'PE': '+51',
    'PF': '+689',
    'PG': '+675',
    'PH': '+63',
    'PK': '+92',
    'PL': '+48',
    'PM': '+508',
    'PR': '+1',
    'PS': '+970',
    'PT': '+351',
    'PW': '+680',
    'PY': '+595',
    'QA': '+974',
    'RE': '+262',
    'RO': '+40',
    'RS': '+381',
    'RU': '+7',
    'RW': '+250',
    'SA': '+966',
    'SB': '+677',
    'SC': '+248',
    'SD': '+249',
    'SE': '+46',
    'SG': '+65',
    'SH': '+290',
    'SI': '+386',
    'SJ': '+47',
    'SK': '+421',
    'SL': '+232',
    'SM': '+378',
    'SN': '+221',
    'SO': '+252',
    'SR': '+597',
    'SS': '+211',
    'ST': '+239',
    'SV': '+503',
    'SX': '+1',
    'SY': '+963',
    'SZ': '+268',
    'TA': '+290',
    'TC': '+1',
    'TD': '+235',
    'TG': '+228',
    'TH': '+66',
    'TJ': '+992',
    'TK': '+690',
    'TL': '+670',
    'TM': '+993',
    'TN': '+216',
    'TO': '+676',
    'TR': '+90',
    'TT': '+1',
    'TV': '+688',
    'TW': '+886',
    'TZ': '+255',
    'UA': '+380',
    'UG': '+256',
    'US': '+1',
    'UY': '+598',
    'UZ': '+998',
    'VA': '+39',
    'VC': '+1',
    'VE': '+58',
    'VG': '+1',
    'VI': '+1',
    'VN': '+84',
    'VU': '+678',
    'WF': '+681',
    'WS': '+685',
    'XK': '+383',
    'YE': '+967',
    'YT': '+262',
    'ZA': '+27',
    'ZM': '+260',
    'ZW': '+263',
}

# A shared calling code resolves to its primary country (E.164 main region).
PREFIX_TO_COUNTRY: dict[str, str] = {
    '+1': 'US',
    '+7': 'RU',
    '+20': 'EG',
    '+27': 'ZA',
    '+30': 'GR',
    '+31': 'NL',
    '+32': 'BE',
    '+33': 'FR',
    '+34': 'ES',
    '+36': 'HU',
    '+39': 'IT',
    '+40': 'RO',
    '+41': 'CH',
    '+43': 'AT',
    '+44': 'GB',
    '+45': 'DK',
    '+46': 'SE',
    '+47': 'NO',
    '+48': 'PL',
    '+49': 'DE',
    '+51': 'PE',
    '+52': 'MX',
    '+53': 'CU',
    '+54': 'AR',
    '+55': 'BR',
    '+56': 'CL',
    '+57': 'CO',
    '+58': 'VE',
    '+60': 'MY',
    '+61': 'AU',
    '+62': 'ID',
    '+63': 'PH',
    '+64': 'NZ',
    '+65': 'SG',
    '+66': 'TH',
    '+81': 'JP',
    '+82': 'KR',
    '+84': 'VN',
    '+86': 'CN',
    '+90': 'TR',
    '+91': 'IN',
    '+92': 'PK',
    '+93': 'AF',
    '+94': 'LK',
    '+95': 'MM',
    '+98': 'IR',
    '+211': 'SS',
    '+212': 'MA',
    '+213': 'DZ',
    '+216': 'TN',
    '+218': 'LY',
    '+220': 'GM',
    '+221': 'SN',
    '+222': 'MR',
    '+223': 'ML',
    '+224': 'GN',
    '+225': 'CI',
    '+226': 'BF',
    '+227': 'NE',
    '+228': 'TG',
    '+229': 'BJ',
    '+230': 'MU',
    '+231': 'LR',
    '+232': 'SL',
    '+233': 'GH',
    '+234': 'NG',
    '+235': 'TD',
    '+236': 'CF',
    '+237': 'CM',
    '+238': 'CV',
    '+239': 'ST',
    '+240': 'GQ',
    '+241': 'GA',
    '+242': 'CG',
    '+243': 'CD',
    '+244': 'AO',
    '+245': 'GW',
    '+246': 'IO',
    '+247': 'AC',
    '+248': 'SC',
    '+249': 'SD',
    '+250': 'RW',
    '+251': 'ET',
    '+252': 'SO',
    '+253': 'DJ',
    '+254': 'KE',
    '+255': 'TZ',
    '+256': 'UG',
    '+257': 'BI',
    '+258': 'MZ',
    '+260': 'ZM',
    '+261': 'MG',
    '+262': 'RE',
    '+263': 'ZW',
    '+264': 'NA',
    '+265': 'MW',
    '+266': 'LS',
    '+267': 'BW',
    '+268': 'SZ',
    '+269': 'KM',
    '+290': 'SH',
    '+291': 'ER',
    '+297': 'AW',
    '+298': 'FO',
    '+299': 'GL',
    '+350': 'GI',
    '+351': 'PT',
    '+352': 'LU',
    '+353': 'IE',
    '+354': 'IS',
    '+355': 'AL',
    '+356': 'MT',
    '+357': 'CY',
    '+358': 'FI',
    '+359': 'BG',
    '+370': 'LT',
    '+371': 'LV',
    '+372': 'EE',
    '+373': 'MD',
    '+374': 'AM',
    '+375': 'BY',
    '+376': 'AD',
    '+377': 'MC',
    '+378': 'SM',
    '+380': 'UA',
    '+381': 'RS',
    '+382': 'ME',
    '+383': 'XK',
    '+385': 'HR',
    '+386': 'SI',
    '+387': 'BA',
    '+389': 'MK',
    '+420': 'CZ',
    '+421': 'SK',
    '+423': 'LI',
    '+500': 'FK',
    '+501': 'BZ',
    '+502': 'GT',
    '+503': 'SV',
    '+504': 'HN',
    '+505': 'NI',
    '+506': 'CR',
    '+507': 'PA',
    '+508': 'PM',
    '+509': 'HT',
    '+590': 'GP',
    '+591': 'BO',
    '+592': 'GY',
    '+593': 'EC',
    '+594': 'GF',
    '+595': 'PY',
    '+596': 'MQ',
    '+597': 'SR',
    '+598': 'UY',
    '+599': 'CW',
    '+670': 'TL',
    '+672': 'NF',
    '+673': 'BN',
    '+674': 'NR',
    '+675': 'PG',
    '+676': 'TO',
    '+677': 'SB',
    '+678': 'VU',
    '+679': 'FJ',
    '+680': 'PW',
    '+681': 'WF',
    '+682': 'CK',
    '+683': 'NU',
    '+685': 'WS',
    '+686': 'KI',
    '+687': 'NC',
    '+688': 'TV',
    '+689': 'PF',
    '+690': 'TK',
    '+691': 'FM',
    '+692': 'MH',
    '+850': 'KP',
    '+852': 'HK',
    '+853': 'MO',
    '+855': 'KH',
    '+856': 'LA',
    '+880': 'BD',
    '+886': 'TW',
    '+960': 'MV',
    '+961': 'LB',
    '+962': 'JO',
    '+963': 'SY',
    '+964': 'IQ',
    '+965': 'KW',
    '+966': 'SA',
    '+967': 'YE',
    '+968': 'OM',
    '+970': 'PS',
    '+971': 'AE',
    '+972': 'IL',
    '+973': 'BH',
    '+974': 'QA',
    '+975': 'BT',
    '+976': 'MN',
    '+977': 'NP',
    '+992': 'TJ',
    '+993': 'TM',
    '+994': 'AZ',
    '+995': 'GE',
    '+996': 'KG',
    '+998': 'UZ',
}

NAMES_EN: dict[str, str] = {
    'AC': 'Ascension Island',
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua & Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AS': 'American Samoa',
    'AT': 'Austria',
    'AU': 'Australia',
    'AW': 'Aruba',
    'AX': 'Åland Islands',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia & Herzegovina',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BL': 'St. Barthélemy',
    'BM': 'Bermuda',
    'BN': 'Brunei',
    'BO': 'Bolivia',
    'BQ': 'Caribbean Netherlands',
    'BR': 'Brazil',
    'BS': 'Bahamas',
    'BT': 'Bhutan',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CC': 'Cocos (Keeling) Islands',
    'CD': 'Congo - Kinshasa',
    'CF': 'Central African Republic',
    'CG': 'Congo - Brazzaville',
    'CH': 'Switzerland',
    'CI': 'Côte d’Ivoire',
    'CK': 'Cook Islands',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CW': 'Curaçao',
    'CX': 'Christmas Island',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands',
    'FM': 'Micronesia',
    'FO': 'Faroe Islands',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GF': 'French Guiana',
    'GG': 'Guernsey',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Greenland',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HK': 'Hong Kong SAR China',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'St. Kitts & Nevis',
    'KP': 'North Korea',
    'KR': 'South Korea',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LB': 'Lebanon',
    'LC': 'St. Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova',
    'ME': 'Montenegro',
    'MF': 'St. Martin',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MM': 'Myanmar (Burma)',
    'MN': 'Mongolia',
    'MO': 'Macao SAR China',
    'MP': 'Northern Mariana Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MS': 'Montserrat',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NC': 'New Caledonia',
    'NE': 'Niger',
    'NF': 'Norfolk Island',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NU': 'Niue',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'French Polynesia',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'St. Pierre & Miquelon',
    'PR': 'Puerto Rico',
    'PS': 'Palestinian Territories',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SH': 'St. Helena',
    'SI': 'Slovenia',
    'SJ': 'Svalbard & Jan Mayen',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'SS': 'South Sudan',
    'ST': 'São Tomé & Príncipe',
    'SV': 'El Salvador',
    'SX': 'Sint Maarten',
    'SY': 'Syria',
    'SZ': 'Eswatini',
    'TA': 'Tristan da Cunha',
    'TC': 'Turks & Caicos Islands',
    'TD': 'Chad',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TK': 'Tokelau',
    'TL': 'Timor-Leste',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TR': 'Türkiye',
    'TT': 'Trinidad & Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TZ': 'Tanzania',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VA': 'Vatican City',
    'VC': 'St. Vincent & Grenadines',
    'VE': 'Venezuela',
    'VG': 'British Virgin Islands',
    'VI': 'U.S. Virgin Islands',
    'VN': 'Vietnam',
    'VU': 'Vanuatu',
    'WF': 'Wallis & Futuna',
    'WS': 'Samoa',
    'XK': 'Kosovo',
    'YE': 'Yemen',
    'YT': 'Mayotte',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
}

NAMES_CS: dict[str, str] = {
    'AC': 'Ascension',
    'AD': 'Andorra',
    'AE': 'Spojené arabské emiráty',
    'AF': 'Afghánistán',
    'AG': 'Antigua a Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albánie',
    'AM': 'Arménie',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AS': 'Americká Samoa',
    'AT': 'Rakousko',
    'AU': 'Austrálie',
    'AW': 'Aruba',
    'AX': 'Ålandy',
    'AZ': 'Ázerbájdžán',
    'BA': 'Bosna a Hercegovina',
    'BB': 'Barbados',
    'BD': 'Bangladéš',
    'BE': 'Belgie',
    'BF': 'Burkina Faso',
    'BG': 'Bulharsko',
    'BH': 'Bahrajn',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BL': 'Svatý Bartoloměj',
    'BM': 'Bermudy',
    'BN': 'Brunej',
    'BO': 'Bolívie',
    'BQ': 'Karibské Nizozemsko',
    'BR': 'Brazílie',
    'BS': 'Bahamy',
    'BT': 'Bhútán',
    'BW': 'Botswana',
    'BY': 'Bělorusko',
    'BZ': 'Belize',
    'CA': 'Kanada',
    'CC': 'Kokosové ostrovy',
    'CD': 'Kongo – Kinshasa',
    'CF': 'Středoafrická republika',
    'CG': 'Kongo – Brazzaville',
    'CH': 'Švýcarsko',
    'CI': 'Pobřeží slonoviny',
    'CK': 'Cookovy ostrovy',
    'CL': 'Chile',
    'CM': 'Kamerun',
    'CN': 'Čína',
    'CO': 'Kolumbie',
    'CR': 'Kostarika',
    'CU': 'Kuba',
    'CV': 'Kapverdy',
    'CW': 'Curaçao',
    'CX': 'Vánoční ostrov',
    'CY': 'Kypr',
    'CZ': 'Česko',
    'DE': 'Německo',
    'DJ': 'Džibutsko',
    'DK': 'Dánsko',
    'DM': 'Dominika',
    'DO': 'Dominikánská republika',
    'DZ': 'Alžírsko',
    'EC': 'Ekvádor',
    'EE': 'Estonsko',
    'EG': 'Egypt',
    'EH': 'Západní Sahara',
    'ER': 'Eritrea',
    'ES': 'Španělsko',
    'ET': 'Etiopie',
    'FI': 'Finsko',
    'FJ': 'Fidži',
    'FK': 'Falklandské ostrovy',
    'FM': 'Mikronésie',
    'FO': 'Faerské ostrovy',
    'FR': 'Francie',
    'GA': 'Gabon',
    'GB': 'Spojené království',
    'GD': 'Grenada',
    'GE': 'Gruzie',
    'GF': 'Francouzská Guyana',
    'GG': 'Guernsey',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Grónsko',
    'GM': 'Gambie',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Rovníková Guinea',
    'GR': 'Řecko',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HK': 'Hongkong – ZAO Číny',
    'HN': 'Honduras',
    'HR': 'Chorvatsko',
    'HT': 'Haiti',
    'HU': 'Maďarsko',
    'ID': 'Indonésie',
    'IE': 'Irsko',
    'IL': 'Izrael',
    'IM': 'Ostrov Man',
    'IN': 'Indie',
    'IO': 'Britské indickooceánské území',
    'IQ': 'Irák',
    'IR': 'Írán',
    'IS': 'Island',
    'IT': 'Itálie',
    'JE': 'Jersey',
    'JM': 'Jamajka',
    'JO': 'Jordánsko',
    'JP': 'Japonsko',
    'KE': 'Keňa',
    'KG': 'Kyrgyzstán',
    'KH': 'Kambodža',
    'KI': 'Kiribati',
    'KM': 'Komory',
    'KN': 'Svatý Kryštof a Nevis',
    'KP': 'Severní Korea',
    'KR': 'Jižní Korea',
    'KW': 'Kuvajt',
    'KY': 'Kajmanské ostrovy',
    'KZ': 'Kazachstán',
    'LA': 'Laos',
    'LB': 'Libanon',
    'LC': 'Svatá Lucie',
    'LI': 'Lichtenštejnsko',
    'LK': 'Srí Lanka',
    'LR': 'Libérie',
    'LS': 'Lesotho',
    'LT': 'Litva',
    'LU': 'Lucembursko',
    'LV': 'Lotyšsko',
    'LY': 'Libye',
    'MA': 'Maroko',
    'MC': 'Monako',
    'MD': 'Moldavsko',
    'ME': 'Černá Hora',
    'MF': 'Svatý Martin (Francie)',
    'MG': 'Madagaskar',
    'MH': 'Marshallovy ostrovy',
    'MK': 'Severní Makedonie',
    'ML': 'Mali',
    'MM': 'Myanmar (Barma)',
    'MN': 'Mongolsko',
    'MO': 'Macao – ZAO Číny',
    'MP': 'Severní Mariany',
    'MQ': 'Martinik',
    'MR': 'Mauritánie',
    'MS': 'Montserrat',
    'MT': 'Malta',
    'MU': 'Mauricius',
    'MV': 'Maledivy',
    'MW': 'Malawi',
    'MX': 'Mexiko',
    'MY': 'Malajsie',
    'MZ': 'Mosambik',
    'NA': 'Namibie',
    'NC': 'Nová Kaledonie',
    'NE': 'Niger',
    'NF': 'Norfolk',
    'NG': 'Nigérie',
    'NI': 'Nikaragua',
    'NL': 'Nizozemsko',
    'NO': 'Norsko',
    'NP': 'Nepál',
    'NR': 'Nauru',
    'NU': 'Niue',
    'NZ': 'Nový Zéland',
    'OM': 'Omán',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'Francouzská Polynésie',
    'PG': 'Papua-Nová Guinea',
    'PH': 'Filipíny',
    'PK': 'Pákistán',
    'PL': 'Polsko',
    'PM': 'Saint-Pierre a Miquelon',
    'PR': 'Portoriko',
    'PS': 'Palestinská území',
    'PT': 'Portugalsko',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Katar',
    'RE': 'Réunion',
    'RO': 'Rumunsko',
    'RS': 'Srbsko',
    'RU': 'Rusko',
    'RW': 'Rwanda',
    'SA': 'Saúdská Arábie',
    'SB': 'Šalamounovy ostrovy',
    'SC': 'Seychely',
    'SD': 'Súdán',
    'SE': 'Švédsko',
    'SG': 'Singapur',
    'SH': 'Svatá Helena',
    'SI': 'Slovinsko',
    'SJ': 'Špicberky a Jan Mayen',
    'SK': 'Slovensko',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somálsko',
    'SR': 'Surinam',
    'SS': 'Jižní Súdán',
    'ST': 'Svatý Tomáš a Princův ostrov',
    'SV': 'Salvador',
    'SX': 'Svatý Martin (Nizozemsko)',
    'SY': 'Sýrie',
    'SZ': 'Eswatini',
    'TA': 'Tristan da Cunha',
    'TC': 'Turks a Caicos',
    'TD': 'Čad',
    'TG': 'Togo',
    'TH': 'Thajsko',
    'TJ': 'Tádžikistán',
    'TK': 'Tokelau',
    'TL': 'Východní Timor',
    'TM': 'Turkmenistán',
    'TN': 'Tunisko',
    'TO': 'Tonga',
    'TR': 'Turecko',
    'TT': 'Trinidad a Tobago',
    'TV': 'Tuvalu',
    'TW': 'Tchaj-wan',
    'TZ': 'Tanzanie',
    'UA': 'Ukrajina',
    'UG': 'Uganda',
    'US': 'Spojené státy',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistán',
    'VA': 'Vatikán',
    'VC': 'Svatý Vincenc a Grenadiny',
    'VE': 'Venezuela',
    'VG': 'Britské Panenské ostrovy',
    'VI': 'Americké Panenské ostrovy',
    'VN': 'Vietnam',
    'VU': 'Vanuatu',
    'WF': 'Wallis a Futuna',
    'WS': 'Samoa',
    'XK': 'Kosovo',
    'YE': 'Jemen',
    'YT': 'Mayotte',
    'ZA': 'Jihoafrická republika',
    'ZM': 'Zambie',
    'ZW': 'Zimbabwe',
}

# --- Curated data -----------------------------------------------------------
ZIP_PATTERNS: dict[str, str] = {
    'AD': 'AD\\d{3}',
    'AL': '\\d{4}',
    'AT': '\\d{4}',
    'BA': '\\d{5}',
    'BE': '\\d{4}',
    'BG': '\\d{4}',
    'CH': '\\d{4}',
    'CY': '\\d{4}',
    'CZ': '\\d{3} ?\\d{2}',
    'DE': '\\d{5}',
    'DK': '\\d{4}',
    'ES': '\\d{5}',
    'FR': '\\d{5}',
    'GB': '[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}',
    'GR': '\\d{3} ?\\d{2}',
    'HR': '\\d{5}',
    'HU': '\\d{4}',
    'IS': '\\d{3}',
    'IT': '\\d{5}',
    'LI': '\\d{4}',
    'LU': '\\d{4}',
    'MC': '980\\d{2}',
    'ME': '\\d{5}',
    'MK': '\\d{4}',
    'MT': '[A-Z]{3} ?\\d{4}',
    'NL': '\\d{4} ?[A-Z]{2}',
    'PL': '\\d{2}-\\d{3}',
    'RO': '\\d{6}',
    'RS': '\\d{5,6}',
    'SI': '\\d{4}',
    'SK': '\\d{3} ?\\d{2}',
    'SM': '4789\\d',
    'VA': '00120',
    'XK': '\\d{5}',
}

COMPANY_SUFFIXES: dict[str, list[str]] = {
    'AT': ['gmbh', 'ag', 'og', 'kg'],
    'BE': ['bvba', 'nv', 'sprl'],
    'BG': ['ood', 'ad', 'eood'],
    'CH': ['ag', 'gmbh', 'sa', 'sàrl'],
    'CZ': ['s.r.o.', 'a.s.', 'spol. s r.o.', 'v.o.s.', 'k.s.', 'z.s.'],
    'DE': ['gmbh', 'ag', 'kg', 'ohg', 'ug', 'e.v.'],
    'DK': ['a/s', 'aps'],
    'ES': ['s.l.', 's.a.', 'slu'],
    'FI': ['oy', 'oyj'],
    'FR': ['sarl', 'sas', 's.a.', 'eurl', 'sci'],
    'GB': ['ltd', 'limited', 'plc', 'llp'],
    'GR': ['ae', 'epe'],
    'HR': ['d.o.o.', 'd.d.'],
    'HU': ['kft', 'zrt', 'nyrt', 'bt', 'kkt'],
    'IE': ['ltd', 'plc'],
    'IT': ['s.r.l.', 's.p.a.', 'snc', 'sas'],
    'NL': ['b.v.', 'n.v.'],
    'NO': ['as', 'asa'],
    'PL': ['sp. z o.o.', 's.a.', 'sp.j.', 'sp.k.'],
    'PT': ['lda', 's.a.'],
    'RO': ['s.r.l.', 's.a.'],
    'RS': ['d.o.o.', 'a.d.'],
    'SE': ['ab'],
    'SI': ['d.o.o.', 'd.d.'],
    'SK': ['s.r.o.', 'a.s.', 'k.s.', 'v.o.s.'],
}

NEIGHBOURS: dict[str, tuple[str, ...]] = {
    'AD': ('ES', 'FR'),
    'AL': ('ME', 'MK', 'GR', 'XK'),
    'AT': ('DE', 'CH', 'CZ', 'SK'),
    'BA': ('HR', 'RS', 'ME'),
    'BE': ('NL', 'FR', 'DE', 'LU'),
    'BG': ('RO', 'GR', 'RS', 'MK'),
    'CH': ('DE', 'AT', 'FR', 'IT'),
    'CY': ('GR',),
    'CZ': ('SK', 'PL', 'DE', 'AT'),
    'DE': ('AT', 'CH', 'NL', 'PL'),
    'DK': ('DE', 'SE', 'NO'),
    'ES': ('FR', 'PT', 'AD'),
    'FR': ('BE', 'CH', 'ES', 'DE'),
    'GB': ('IE', 'FR', 'NL', 'DE'),
    'GR': ('BG', 'MK', 'AL', 'IT'),
    'HR': ('SI', 'HU', 'RS', 'BA'),
    'HU': ('SK', 'AT', 'RO', 'RS'),
    'IE': ('GB',),
    'IS': ('DK', 'NO'),
    'IT': ('CH', 'AT', 'SI', 'FR'),
    'LI': ('CH', 'AT'),
    'LU': ('BE', 'DE', 'FR'),
    'MC': ('FR', 'IT'),
    'ME': ('RS', 'BA', 'AL', 'XK'),
    'MK': ('RS', 'BG', 'GR', 'AL'),
    'MT': ('IT',),
    'NL': ('BE', 'DE', 'GB', 'LU'),
    'PL': ('CZ', 'SK', 'DE', 'LT'),
    'PT': ('ES',),
    'RO': ('HU', 'BG', 'RS', 'MD'),
    'RS': ('HR', 'BA', 'ME', 'MK'),
    'SI': ('AT', 'IT', 'HR', 'HU'),
    'SK': ('CZ', 'PL', 'AT', 'HU'),
    'SM': ('IT',),
    'VA': ('IT',),
    'XK': ('RS', 'MK', 'AL', 'ME'),
}
