# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 AVANTRO s.r.o.
"""
Regenerate `foxentry/countries.py`.

MAINTAINER TOOL - not part of the application and not shipped in the build. It runs on a
maintainer's machine, never on a user's: the application must never fetch reference data at
runtime, so the generated module is committed to the repository and baked into the binary.

    pip install phonenumbers Babel
    git clone https://github.com/Foxentry/OAS ../OAS

    python tools/update_countries.py --oas ../OAS            # rewrite foxentry/countries.py
    python tools/update_countries.py --oas ../OAS --check    # verify it is up to date (CI)

The output is deterministic: no timestamps, everything sorted. Running it twice on the same
inputs produces the same bytes, so `--check` is a reliable drift test and anyone can
reproduce the committed module from its stated sources.

Where the data comes from
-------------------------
* Service coverage - the `dataSource` defaults in the Foxentry OpenAPI specification
  (github.com/Foxentry/OAS). The live source behind those defaults is
  `/projects/v1/service/{service}/enabled-countries`, which the OAS repository syncs itself.
* Calling codes and their primary country - ITU-T E.164, via `phonenumbers`. Non-geographic
  codes (+800 toll-free, +870 Inmarsat, ...) are skipped: they belong to no country and would
  only produce false detections.
* Country names, English and Czech - CLDR, via `Babel`.

Curated below, because no machine-readable source for them is worth a dependency:
postal-code shapes, company legal-form suffixes and neighbouring countries. They are data,
not code - change them here, then regenerate.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

try:
    from babel import Locale
    from phonenumbers.phonenumberutil import COUNTRY_CODE_TO_REGION_CODE
except ImportError:
    sys.exit("Missing build dependencies. Run: pip install phonenumbers Babel")

BANNER = "GENERATED by tools/update_countries.py - do not edit by hand."

# CLDR's pseudo-territory for "world / not a country". It carries the non-geographic
# calling codes, and a detector must never conclude that a number is "from 001".
NON_GEOGRAPHIC = "001"

# The services whose coverage is a country list. `email` and `phone` are worldwide and take
# no country at all, so they are not read from the OAS.
OAS_OPTIONS = {
    "location": "components/schemas/requests/location/LocationOptions.yaml",
    "company": "components/schemas/requests/company/CompanyOptions.yaml",
    "name": "components/schemas/requests/name/NameValidationBody.yaml",
}

# Whether a country outside a service's coverage fails hard. Registers (companies, addresses)
# return "invalid" for every row; the name database still recognises a foreign name, only
# less reliably - so the two cannot carry the same warning.
STRICT = {"location": True, "company": True, "name": False}


# --- Curated data -----------------------------------------------------------
# Postal-code shape per country. Used to detect the country from the data, so the patterns
# are deliberately shape-only: they say what a code looks like, not whether it exists.
ZIP_PATTERNS = {
    'AD': 'AD\\d{3}',
    'AL': '\\d{4}',
    'AT': '\\d{4}',
    'BA': '\\d{5}',
    'BE': '\\d{4}',
    'BG': '\\d{4}',
    'CH': '\\d{4}',
    'CY': '\\d{4}',
    'CZ': '\\d{3} ?\\d{2}',
    'DE': '\\d{5}',
    'DK': '\\d{4}',
    'ES': '\\d{5}',
    'FR': '\\d{5}',
    'GB': '[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}',
    'GR': '\\d{3} ?\\d{2}',
    'HR': '\\d{5}',
    'HU': '\\d{4}',
    'IS': '\\d{3}',
    'IT': '\\d{5}',
    'LI': '\\d{4}',
    'LU': '\\d{4}',
    'MC': '980\\d{2}',
    'ME': '\\d{5}',
    'MK': '\\d{4}',
    'MT': '[A-Z]{3} ?\\d{4}',
    'NL': '\\d{4} ?[A-Z]{2}',
    'PL': '\\d{2}-\\d{3}',
    'RO': '\\d{6}',
    'RS': '\\d{5,6}',
    'SI': '\\d{4}',
    'SK': '\\d{3} ?\\d{2}',
    'SM': '4789\\d',
    'VA': '00120',
    'XK': '\\d{5}',
}

COMPANY_SUFFIXES = {
    'AT': ['gmbh', 'ag', 'og', 'kg'],
    'BE': ['bvba', 'nv', 'sprl'],
    'BG': ['ood', 'ad', 'eood'],
    'CH': ['ag', 'gmbh', 'sa', 'sàrl'],
    'CZ': ['s.r.o.', 'a.s.', 'spol. s r.o.', 'v.o.s.', 'k.s.', 'z.s.'],
    'DE': ['gmbh', 'ag', 'kg', 'ohg', 'ug', 'e.v.'],
    'DK': ['a/s', 'aps'],
    'ES': ['s.l.', 's.a.', 'slu'],
    'FI': ['oy', 'oyj'],
    'FR': ['sarl', 'sas', 's.a.', 'eurl', 'sci'],
    'GB': ['ltd', 'limited', 'plc', 'llp'],
    'GR': ['ae', 'epe'],
    'HR': ['d.o.o.', 'd.d.'],
    'HU': ['kft', 'zrt', 'nyrt', 'bt', 'kkt'],
    'IE': ['ltd', 'plc'],
    'IT': ['s.r.l.', 's.p.a.', 'snc', 'sas'],
    'NL': ['b.v.', 'n.v.'],
    'NO': ['as', 'asa'],
    'PL': ['sp. z o.o.', 's.a.', 'sp.j.', 'sp.k.'],
    'PT': ['lda', 's.a.'],
    'RO': ['s.r.l.', 's.a.'],
    'RS': ['d.o.o.', 'a.d.'],
    'SE': ['ab'],
    'SI': ['d.o.o.', 'd.d.'],
    'SK': ['s.r.o.', 'a.s.', 'k.s.', 'v.o.s.'],
}

NEIGHBOURS = {
    'AD': ('ES', 'FR'),
    'AL': ('ME', 'MK', 'GR', 'XK'),
    'AT': ('DE', 'CH', 'CZ', 'SK'),
    'BA': ('HR', 'RS', 'ME'),
    'BE': ('NL', 'FR', 'DE', 'LU'),
    'BG': ('RO', 'GR', 'RS', 'MK'),
    'CH': ('DE', 'AT', 'FR', 'IT'),
    'CY': ('GR',),
    'CZ': ('SK', 'PL', 'DE', 'AT'),
    'DE': ('AT', 'CH', 'NL', 'PL'),
    'DK': ('DE', 'SE', 'NO'),
    'ES': ('FR', 'PT', 'AD'),
    'FR': ('BE', 'CH', 'ES', 'DE'),
    'GB': ('IE', 'FR', 'NL', 'DE'),
    'GR': ('BG', 'MK', 'AL', 'IT'),
    'HR': ('SI', 'HU', 'RS', 'BA'),
    'HU': ('SK', 'AT', 'RO', 'RS'),
    'IE': ('GB',),
    'IS': ('DK', 'NO'),
    'IT': ('CH', 'AT', 'SI', 'FR'),
    'LI': ('CH', 'AT'),
    'LU': ('BE', 'DE', 'FR'),
    'MC': ('FR', 'IT'),
    'ME': ('RS', 'BA', 'AL', 'XK'),
    'MK': ('RS', 'BG', 'GR', 'AL'),
    'MT': ('IT',),
    'NL': ('BE', 'DE', 'GB', 'LU'),
    'PL': ('CZ', 'SK', 'DE', 'LT'),
    'PT': ('ES',),
    'RO': ('HU', 'BG', 'RS', 'MD'),
    'RS': ('HR', 'BA', 'ME', 'MK'),
    'SI': ('AT', 'IT', 'HR', 'HU'),
    'SK': ('CZ', 'PL', 'AT', 'HU'),
    'SM': ('IT',),
    'VA': ('IT',),
    'XK': ('RS', 'MK', 'AL', 'ME'),
}



# --- The module we emit -----------------------------------------------------
# Everything that is code rather than data is kept here verbatim. The emitter only fills in
# the tables, so the generated module stays reviewable and diffable.
MODULE_HEAD = """# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 AVANTRO s.r.o.
\"\"\"
Static country reference data.

This module is GENERATED - do not edit by hand. Reproduce it with:

    pip install phonenumbers Babel
    python tools/update_countries.py --oas <path to a checkout of github.com/Foxentry/OAS>

The generator is deterministic: same inputs, same bytes. `--check` verifies that this file
is up to date without writing anything, which is what CI runs.

The data is baked into the build on purpose: the application must never reach out
to the network at runtime except for the validation calls the user explicitly starts.
Sources: the Foxentry OpenAPI specification (per-service `dataSource` defaults),
ITU-T E.164 calling codes and their primary countries (via `phonenumbers`), and CLDR country
names (via `Babel`). Postal-code shapes, legal-form suffixes and neighbouring countries are
curated in the generator.

Contents
--------
COVERAGE          which countries each Foxentry service supports
CALLING_CODES     ISO 3166-1 alpha-2 -> E.164 calling code
PREFIX_TO_COUNTRY calling code -> the country we treat as primary for detection
NAMES_EN/NAMES_CS country names (English is the default; Czech is a translation)
ZIP_PATTERNS      postal-code shape per country (used to detect the country from data)
COMPANY_SUFFIXES  legal-form suffixes per country (weak detection signal)
NEIGHBOURS        neighbouring countries (used when ranking phone prefixes)
\"\"\"

from __future__ import annotations

import re

WORLDWIDE = "worldwide"
"""

MODULE_HELPERS = """def is_strict(service: str) -> bool:
    return STRICT_COVERAGE.get(service, True)


def supports(service: str, country: str | None) -> bool:
    \"\"\"True when the service can validate data from that country.\"\"\"
    cov = COVERAGE.get(service, WORLDWIDE)
    if cov == WORLDWIDE:
        return True
    if not country:
        return True  # no country chosen -> the API searches every source
    return country.upper() in cov


def covered_countries(service: str) -> list[str]:
    \"\"\"The countries a service covers ([] means worldwide).\"\"\"
    cov = COVERAGE.get(service, WORLDWIDE)
    return [] if cov == WORLDWIDE else list(cov)


# --- Names ------------------------------------------------------------------
def name(code: str, lang: str = "en") -> str:
    \"\"\"Country name in the requested language; English is the fallback.\"\"\"
    code = (code or "").upper()
    if lang == "cs":
        return NAMES_CS.get(code) or NAMES_EN.get(code) or code
    return NAMES_EN.get(code) or code


def flag(code: str) -> str:
    \"\"\"Regional-indicator flag emoji for an alpha-2 code.\"\"\"
    code = (code or "").upper()
    if not re.fullmatch(r"[A-Z]{2}", code):
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - 65) for ch in code)


# --- Phone prefixes ---------------------------------------------------------
def prefix_of(country: str | None) -> str | None:
    \"\"\"E.164 calling code for a country, e.g. "CZ" -> "+420".\"\"\"
    return CALLING_CODES.get((country or "").upper())


def country_of_prefix(number: str) -> str | None:
    \"\"\"
    Country for a phone number written with an international prefix.
    Longest match wins, so "+420" beats "+42".
    \"\"\"
    value = re.sub(r"[^\\d+]", "", number or "")
    if not value.startswith("+"):
        return None
    for length in range(5, 1, -1):
        hit = PREFIX_TO_COUNTRY.get(value[:length])
        if hit:
            return hit
    return None


def prefix_order(country: str | None) -> list[str]:
    \"\"\"
    Preferred prefixes for the API, most likely first.

    Only used for numbers written WITHOUT a prefix: the API picks the first
    prefix from this list that makes the number valid.
    \"\"\"
    order: list[str] = []
    own = prefix_of(country)
    if own:
        order.append(own)
    for neighbour in NEIGHBOURS.get((country or "").upper(), ()):
        pfx = prefix_of(neighbour)
        if pfx and pfx not in order:
            order.append(pfx)
    return order


# --- Postal codes -----------------------------------------------------------
def zip_matches(country: str, value: str) -> bool:
    \"\"\"True when the value has the shape of that country's postal code.\"\"\"
    pattern = ZIP_PATTERNS.get((country or "").upper())
    if not pattern or not value:
        return False
    return bool(re.fullmatch(pattern, value.strip(), re.IGNORECASE))


def countries_matching_zip(value: str) -> list[str]:
    \"\"\"Every country whose postal-code shape the value fits.\"\"\"
    value = (value or "").strip()
    if not value:
        return []
    return [cc for cc, pat in ZIP_PATTERNS.items()
            if re.fullmatch(pat, value, re.IGNORECASE)]
"""


# --- Reading the sources ----------------------------------------------------
def read_coverage(oas_root: pathlib.Path) -> dict[str, list[str]]:
    """Pull each service's `dataSource` default out of the OpenAPI schema files."""
    coverage: dict[str, list[str]] = {}
    for service, relative in OAS_OPTIONS.items():
        path = oas_root / relative
        if not path.exists():
            sys.exit(f"OAS file not found: {path}\n"
                     f"Pass --oas <path to a checkout of github.com/Foxentry/OAS>")
        text = path.read_text(encoding="utf-8")
        match = re.search(r"dataSource:.*?default:\n((?:\s*-\s*\w+\n)+)", text, re.S)
        if not match:
            sys.exit(f"No `dataSource` default found in {path}")
        coverage[service] = sorted(set(re.findall(r"-\s*(\w+)", match.group(1))))
    return coverage


def read_calling_codes() -> tuple[dict[str, str], dict[str, str]]:
    """E.164, from `phonenumbers`.

    Returns (country -> calling code, calling code -> its primary country). Several countries
    share a code (+1, +7, +44); `phonenumbers` lists the main region first, and that is the one
    a detector should guess.
    """
    calling: dict[str, str] = {}
    primary: dict[str, str] = {}
    for code, regions in COUNTRY_CODE_TO_REGION_CODE.items():
        regions = [r for r in regions if r != NON_GEOGRAPHIC]
        if not regions:
            continue
        for region in regions:
            calling[region] = f"+{code}"
        primary[f"+{code}"] = regions[0]
    return dict(sorted(calling.items())), dict(sorted(primary.items(), key=_prefix_key))


def _prefix_key(item: tuple[str, str]) -> tuple[int, str]:
    return (len(item[0]), item[0])


def read_names(codes: list[str]) -> tuple[dict[str, str], dict[str, str]]:
    """Country names from CLDR. English is the default; Czech is a translation."""
    en, cs = Locale("en"), Locale("cs")
    missing = [c for c in codes if not en.territories.get(c)]
    if missing:
        sys.exit(f"CLDR has no English name for: {', '.join(missing)}")
    return ({c: en.territories[c] for c in codes},
            {c: cs.territories.get(c) or en.territories[c] for c in codes})


# --- Emitting ---------------------------------------------------------------
def _dict_literal(name: str, data: dict, annotation: str, comment: str = "") -> str:
    body = "\n".join(f"    {k!r}: {v!r}," for k, v in data.items())
    head = f"{comment}\n" if comment else ""
    return f"{head}{name}: {annotation} = {{\n{body}\n}}\n"


def render(coverage: dict[str, list[str]]) -> str:
    calling, primary = read_calling_codes()
    names_en, names_cs = read_names(list(calling))

    full_coverage: dict[str, object] = {"email": "worldwide", "phone": "worldwide"}
    for service in ("name", "company", "location"):
        full_coverage[service] = coverage[service]

    parts = [
        MODULE_HEAD,
        "# --- Service coverage -------------------------------------------------------\n"
        "# Mirrors the `dataSource` defaults in the Foxentry OpenAPI specification.\n"
        "# Sending a country a service does not cover only burns credits and returns\n"
        '# "invalid" for every row, so the wizard warns the user up front.\n'
        + _dict_literal("COVERAGE", full_coverage, "dict[str, list[str] | str]")
        .replace("'worldwide'", "WORLDWIDE"),
        _dict_literal("STRICT_COVERAGE", STRICT, "dict[str, bool]",
                      "# Whether an uncovered country fails hard (a register) or merely degrades\n"
                      "# (reference data such as names)."),
        MODULE_HELPERS,
        "# --- Generated data ---------------------------------------------------------",
        _dict_literal("CALLING_CODES", calling, "dict[str, str]"),
        _dict_literal("PREFIX_TO_COUNTRY", primary, "dict[str, str]",
                      "# A shared calling code resolves to its primary country (E.164 main region)."),
        _dict_literal("NAMES_EN", names_en, "dict[str, str]"),
        _dict_literal("NAMES_CS", names_cs, "dict[str, str]"),
        "# --- Curated data -----------------------------------------------------------",
        _dict_literal("ZIP_PATTERNS", ZIP_PATTERNS, "dict[str, str]"),
        _dict_literal("COMPANY_SUFFIXES", COMPANY_SUFFIXES, "dict[str, list[str]]"),
        _dict_literal("NEIGHBOURS", NEIGHBOURS, "dict[str, tuple[str, ...]]"),
    ]
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate foxentry/countries.py")
    parser.add_argument("--oas", required=True, type=pathlib.Path,
                        help="path to a checkout of github.com/Foxentry/OAS")
    parser.add_argument("--out", type=pathlib.Path,
                        default=pathlib.Path("foxentry/countries.py"))
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if the file on disk is out of date")
    args = parser.parse_args()

    coverage = read_coverage(args.oas)
    for service, codes in coverage.items():
        print(f"  {service:9} {len(codes):2} countries from the OAS: {', '.join(codes)}")

    text = render(coverage)

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            sys.exit(f"\n{args.out} is out of date. Run: python tools/update_countries.py --oas <OAS>")
        print(f"\n{args.out} is up to date.")
        return

    args.out.write_text(text, encoding="utf-8")
    print(f"\nWrote {args.out} ({len(text.splitlines())} lines).")


if __name__ == "__main__":
    main()
